import {WalletApi2} from 'types'

// This currently contains 3 demo wallets to mock the api response while api auth functionality is being built

const getDemoWallet0Response: WalletApi2 = { // Viator wallet
  'joins': [],
  'loyalty_cards': [
    {
      'id': 351941,
      'loyalty_plan_id': 292,
      'loyalty_plan_name': 'Viator Discounts',
      'is_fully_pll_linked': true,
      'pll_linked_payment_accounts': 1,
      'total_payment_accounts': 1,
      'status': {
        'state': 'authorised',
        'slug': null,
        'description': null,
      },
      'balance': {
        'updated_at': 1690378214,
        'current_display_value': '£0',
        'loyalty_currency_name': 'GBP',
        'prefix': '£',
        'suffix': null,
        'current_value': '0',
        'target_value': '200',
      },
      'transactions': [],
      'vouchers': [
        {
          'state': 'inprogress',
          'earn_type': 'accumulator',
          'reward_text': '10% off discount',
          'headline': 'Spend £200 to get a 10% off Viator voucher code',
          'voucher_code': null,
          'barcode_type': null,
          'progress_display_text': '£100/£200',
          'current_value': '100',
          'target_value': '200',
          'prefix': '£',
          'suffix': null,
          'body_text': 'Congratulations! You have earned a reward to use at Viator, with more than 300,000 experiences available to book. Do More With Viator!',
          'terms_and_conditions': 'https://policies.gb.bink.com/Viator/rewardtc.html',
          'issued_date': null,
          'expiry_date': null,
          'redeemed_date': null,
          'conversion_date': null,
        },
        {
          'state': 'issued',
          'earn_type': 'accumulator',
          'reward_text': '10% off discount',
          'headline': 'Earned',
          'voucher_code': 'ohbeg',
          'barcode_type': null,
          'progress_display_text': '£200/£200',
          'current_value': '200',
          'target_value': '200',
          'prefix': '£',
          'suffix': null,
          'body_text': 'Congratulations! You have earned a reward to use at Viator, with more than 300,000 experiences available to book. Do More With Viator!',
          'terms_and_conditions': 'https://policies.staging.gb.bink.com/Viator/rewardtc.html',
          'issued_date': '1692785701',
          'expiry_date': '1695600000',
          'redeemed_date': null,
          'conversion_date': null,
        },
      ],
      'card': {
        'barcode': null,
        'barcode_type': null,
        'card_number': 'VIAT2542564215',
        'colour': '#246b6c',
        'text_colour': '#FFFFFF',
      },
      'reward_available': false,
      'images': [
        {
          'id': 1411,
          'type': 3,
          'url': 'https://api.gb.bink.com/content/media/hermes/schemes/Logo1-280x280.png',
          'description': 'Viator Logo',
          'encoding': 'png',
          'cta_url': null,
        },
        {
          'id': 1409,
          'type': 0,
          'url': 'https://api.gb.bink.com/content/media/hermes/schemes/Loyalty_Card_V2_1312x800.png',
          'description': 'Viator Loyalty Card',
          'encoding': 'png',
          'cta_url': null,
        },
        {
          'id': 1412,
          'type': 7,
          'url': 'https://api.gb.bink.com/content/media/hermes/schemes/Viator_Barclays_Promotional_Image.png',
          'description': 'Viator Promotion',
          'encoding': 'png',
          'cta_url': null,
        },
      ],
      'pll_links': [
        {
          'payment_account_id': 89160,
          'payment_scheme': 'Visa',
          'status': {
            'state': 'active',
            'slug': null,
            'description': null,
          },
        },
      ],
    },
  ],
  'payment_accounts': [
    {
      'id': 89160,
      'provider': 'Visa',
      'issuer': 'Barclays',
      'status': 'active',
      'expiry_month': '12',
      'expiry_year': '25',
      'name_on_card': 'lukie',
      'card_nickname': 'My card',
      'type': 'debit',
      'currency_code': 'GBP',
      'country': 'GB',
      'last_four_digits': '5019',
      'images': [
        {
          'id': 55,
          'type': 0,
          'url': 'https://api.gb.bink.com/content/media/hermes/schemes/Visa-Payment_Eq81MWN.png',
          'description': 'Visa Card Image',
          'encoding': 'png',
        },
      ],
      'pll_links': [
        {
          'loyalty_card_id': 351941,
          'loyalty_plan': 'Viator Discounts',
          'status': {
            'state': 'active',
            'slug': null,
            'description': null,
          },
        },
      ],
    },
  ],
}
const getDemoWallet1Response: WalletApi2 = {
  'joins': [],
  'loyalty_cards': [{
    'id': 363711,
    'loyalty_plan_id': 291,
    'loyalty_plan_name': 'Loyalteas Plus',
    'is_fully_pll_linked': true,
    'pll_linked_payment_accounts': 1,
    'total_payment_accounts': 1,
    'status': {
      'state': 'authorised',
      'slug': null,
      'description': null,
    },
    'balance': {
      'updated_at': 1690815508,
      'current_display_value': '0 stamps',
      'loyalty_currency_name': 'stamps',
      'prefix': null,
      'suffix': 'stamps',
      'current_value': '0',
      'target_value': '5',
    },
    'transactions': [],
    'vouchers': [{
      'state': 'inprogress',
      'earn_type': 'stamps',
      'reward_text': 'Free Box of Teabags',
      'headline': '5.0 stamps to go!',
      'voucher_code': null,
      'barcode_type': 0,
      'progress_display_text': '0/5 stamps',
      'current_value': '0',
      'target_value': '5',
      'prefix': null,
      'suffix': 'stamps',
      'body_text': '{{earn_target_remaining}} stamps to go!',
      'terms_and_conditions': 'https://policies.gb.bink.com/loyalteas/tc.html',
      'issued_date': null,
      'expiry_date': null,
      'redeemed_date': null,
      'conversion_date': null,
    }],
    'card': {
      'barcode': null,
      'barcode_type': 0,
      'card_number': 'CORT1268778716',
      'colour': '#439190',
      'text_colour': null,
    },
    'reward_available': false,
    'images': [{
      'id': 1406,
      'type': 0,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/loyalteas-hero.png',
      'description': 'Loyalteas Hero',
      'encoding': 'png',
      'cta_url': null,
    },
    {
      'id': 1408,
      'type': 3,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/loyalteas-icon.png',
      'description': 'Loyalteas Icon',
      'encoding': 'png',
      'cta_url': null,
    }],
    'pll_links': [{
      'payment_account_id': 238288,
      'payment_scheme': 'Visa',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    }],
  },
  {
    'id': 363710,
    'loyalty_plan_id': 284,
    'loyalty_plan_name': 'Bink Sweet Rewards',
    'is_fully_pll_linked': true,
    'pll_linked_payment_accounts': 1,
    'total_payment_accounts': 1,
    'status': {
      'state': 'authorised',
      'slug': null,
      'description': null,
    },
    'balance': {
      'updated_at': 1690815458,
      'current_display_value': '£0',
      'loyalty_currency_name': 'GBP',
      'prefix': '£',
      'suffix': null,
      'current_value': '0',
      'target_value': '100',
    },
    'transactions': [],
    'vouchers': [{
      'state': 'inprogress',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': '£100.00 to go!',
      'voucher_code': null,
      'barcode_type': 0,
      'progress_display_text': '£0/£100',
      'current_value': '0',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': '£{{earn_target_remaining|floatformat:"2"}} to go!',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': null,
      'expiry_date': null,
      'redeemed_date': null,
      'conversion_date': null,
    }],
    'card': {
      'barcode': null,
      'barcode_type': 0,
      'card_number': 'TRNT6041395265',
      'colour': '#532f91',
      'text_colour': null,
    },
    'reward_available': false,
    'images': [{
      'id': 1321,
      'type': 0,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/binksweetshop-hero.png',
      'description': 'Bink Sweet Rewards Hero',
      'encoding': 'png',
      'cta_url': null,
    },
    {
      'id': 1322,
      'type': 3,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/binksweetshop-icon.png',
      'description': 'Bink Sweet Rewards Icon',
      'encoding': 'png',
      'cta_url': null,
    }],
    'pll_links': [{
      'payment_account_id': 238288,
      'payment_scheme': 'Visa',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    }],
  }],
  'payment_accounts': [{
    'id': 238288,
    'provider': 'Visa',
    'issuer': 'Barclays',
    'status': 'active',
    'expiry_month': '12',
    'expiry_year': '25',
    'name_on_card': 'Portal Dev',
    'card_nickname': 'Visa Card',
    'type': 'debit',
    'currency_code': 'GBP',
    'country': 'GB',
    'last_four_digits': '4242',
    'images': [{
      'id': 55,
      'type': 0,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/Visa-Payment_Eq81MWN.png',
      'description': 'Visa Card Image',
      'encoding': 'png',
    }],
    'pll_links': [{
      'loyalty_card_id': 363710,
      'loyalty_plan': 'Bink Sweet Rewards',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    },
    {
      'loyalty_card_id': 363711,
      'loyalty_plan': 'Loyalteas Plus',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    }],
  }],
}

const getDemoWallet2Response = {
  'joins': [],
  'loyalty_cards': [{
    'id': 363707,
    'loyalty_plan_id': 284,
    'loyalty_plan_name': 'Bink Sweet Rewards',
    'is_fully_pll_linked': true,
    'pll_linked_payment_accounts': 1,
    'total_payment_accounts': 1,
    'status': {
      'state': 'authorised',
      'slug': null,
      'description': null,
    },
    'balance': {
      'updated_at': 1691653191,
      'current_display_value': '£50',
      'loyalty_currency_name': 'GBP',
      'prefix': '£',
      'suffix': null,
      'current_value': '50',
      'target_value': '100',
    },
    'transactions': [{
      'id': '803957',
      'timestamp': 1691652617,
      'description': 'N/A -£5.00',
      'display_value': '-£5',
    },
    {
      'id': '803958',
      'timestamp': 1691652521,
      'description': 'N/A -£95.00',
      'display_value': '-£95',
    },
    {
      'id': '803959',
      'timestamp': 1691652521,
      'description': 'N/A £35.99',
      'display_value': '£35.99',
    },
    {
      'id': '803960',
      'timestamp': 1691652521,
      'description': 'N/A £64.01',
      'display_value': '£64.01',
    },
    {
      'id': '803961',
      'timestamp': 1691398754,
      'description': 'N/A £100.00',
      'display_value': '£100',
    }],
    'vouchers': [{
      'state': 'inprogress',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': '£50.00 to go!',
      'voucher_code': null,
      'barcode_type': 0,
      'progress_display_text': '£50/£100',
      'current_value': '50',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': '£{{earn_target_remaining|floatformat:"2"}} to go!',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': null,
      'expiry_date': null,
      'redeemed_date': null,
      'conversion_date': null,
    },
    {
      'state': 'pending',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': 'Pending',
      'voucher_code': 'pending',
      'barcode_type': 0,
      'progress_display_text': '£100/£100',
      'current_value': '100',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': 'You have earned a voucher, but it\'s not ready yet. Check back tomorrow for your code.',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': '1691625600',
      'expiry_date': null,
      'redeemed_date': null,
      'conversion_date': '1691712000',
    },
    {
      'state': 'cancelled',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': 'Cancelled',
      'voucher_code': 'Trenette-campaign2-24',
      'barcode_type': 0,
      'progress_display_text': '£100/£100',
      'current_value': '100',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': 'Your voucher has been cancelled.',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': '1690806602',
      'expiry_date': '1698582602',
      'redeemed_date': null,
      'conversion_date': null,
    },
    {
      'state': 'expired',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': 'Expired',
      'voucher_code': 'Trenette-campaign2-66',
      'barcode_type': 0,
      'progress_display_text': '£100/£100',
      'current_value': '100',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': 'Your voucher has expired.',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': '1690806601',
      'expiry_date': '1690806601',
      'redeemed_date': null,
      'conversion_date': null,
    },
    {
      'state': 'redeemed',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': 'Redeemed',
      'voucher_code': 'Trenette-campaign2-67',
      'barcode_type': 0,
      'progress_display_text': '£100/£100',
      'current_value': '100',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': 'Your voucher has been redeemed.',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': '1690806601',
      'expiry_date': '1698582601',
      'redeemed_date': '1690810560',
      'conversion_date': null,
    },
    {
      'state': 'issued',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': 'Earned',
      'voucher_code': 'Trenette-campaign2-52',
      'barcode_type': 0,
      'progress_display_text': '£100/£100',
      'current_value': '100',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': 'Show your voucher at checkout for your free chocolate hamper.',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': '1690806600',
      'expiry_date': '1761913800',
      'redeemed_date': null,
      'conversion_date': null,
    },
    {
      'state': 'pending',
      'earn_type': 'accumulator',
      'reward_text': 'Free Chocolate Hamper',
      'headline': 'Pending',
      'voucher_code': 'pending',
      'barcode_type': 0,
      'progress_display_text': '£100/£100',
      'current_value': '100',
      'target_value': '100',
      'prefix': '£',
      'suffix': null,
      'body_text': 'You have earned a voucher,but it\'s not ready yet. Check back tomorrow for your code.',
      'terms_and_conditions': 'https://policies.gb.bink.com/trenette/tc.html',
      'issued_date': '1690761600',
      'expiry_date': null,
      'redeemed_date': null,
      'conversion_date': '1756598400',
    }],
    'card': {
      'barcode': null,
      'barcode_type': 0,
      'card_number': 'TRNT1586503672',
      'colour': '#532f91',
      'text_colour': null,
    },
    'reward_available': true,
    'images': [{
      'id': 1321,
      'type': 0,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/binksweetshop-hero.png',
      'description': 'Bink Sweet Rewards Hero',
      'encoding': 'png',
      'cta_url': null,
    },
    {
      'id': 1322,
      'type': 3,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/binksweetshop-icon.png',
      'description': 'Bink Sweet Rewards Icon',
      'encoding': 'png',
      'cta_url': null,
    }],
    'pll_links': [{
      'payment_account_id': 120802,
      'payment_scheme': 'Visa',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    }],
  },
  {
    'id': 363709,
    'loyalty_plan_id': 291,
    'loyalty_plan_name': 'Loyalteas Plus',
    'is_fully_pll_linked': true,
    'pll_linked_payment_accounts': 1,
    'total_payment_accounts': 1,
    'status': {
      'state': 'authorised',
      'slug': null,
      'description': null,
    },
    'balance': {
      'updated_at': 1691653962,
      'current_display_value': '1 stamps',
      'loyalty_currency_name': 'stamps',
      'prefix': null,
      'suffix': 'stamps',
      'current_value': '1',
      'target_value': '5',
    },
    'transactions': [{
      'id': '803962',
      'timestamp': 1691653755,
      'description': 'Loyalteas £24.31',
      'display_value': '1 stamps',
    },
    {
      'id': '803963',
      'timestamp': 1691653755,
      'description': 'Loyalteas £9.99',
      'display_value': '1 stamps',
    },
    {
      'id': '803964',
      'timestamp': 1691653651,
      'description': 'Loyalteas £7.99',
      'display_value': '1 stamps',
    },
    {
      'id': '803965',
      'timestamp': 1691653651,
      'description': 'Loyalteas £6.50',
      'display_value': '1 stamps',
    },
    {
      'id': '803966',
      'timestamp': 1691652617,
      'description': 'Loyalteas £5.00',
      'display_value': '1 stamps',
    }],
    'vouchers': [{
      'state': 'inprogress',
      'earn_type': 'stamps',
      'reward_text': 'Free Box of Teabags',
      'headline': '4.0 stamps to go!',
      'voucher_code': null,
      'barcode_type': 0,
      'progress_display_text': '1/5 stamps',
      'current_value': '1',
      'target_value': '5',
      'prefix': null,
      'suffix': 'stamps',
      'body_text': '{{earn_target_remaining}} stamps to go!',
      'terms_and_conditions': 'https://policies.gb.bink.com/loyalteas/tc.html',
      'issued_date': null,
      'expiry_date': null,
      'redeemed_date': null,
      'conversion_date': null,
    },
    {
      'state': 'issued',
      'earn_type': 'stamps',
      'reward_text': 'Free Box of Teabags',
      'headline': 'Earned',
      'voucher_code': 'ddc85cb4-10b3-41a6-a254-35facaf633b7',
      'barcode_type': 0,
      'progress_display_text': '5/5 stamps',
      'current_value': '5',
      'target_value': '5',
      'prefix': null,
      'suffix': 'stamps',
      'body_text': 'Show your reward code in store to redeem a free box of teabags.',
      'terms_and_conditions': 'https://policies.gb.bink.com/loyalteas/tc.html',
      'issued_date': '1691653762',
      'expiry_date': '1691740162',
      'redeemed_date': null,
      'conversion_date': null,
    },
    {
      'state': 'expired',
      'earn_type': 'stamps',
      'reward_text': 'Free Box of Teabags',
      'headline': 'Expired',
      'voucher_code': 'ddc85cb4-10b3-41a6-a254-35facaf633e7',
      'barcode_type': 0,
      'progress_display_text': '5/5 stamps',
      'current_value': '5',
      'target_value': '5',
      'prefix': null,
      'suffix': 'stamps',
      'body_text': 'Your voucher has expired.',
      'terms_and_conditions': 'https://policies.gb.bink.com/loyalteas/tc.html',
      'issued_date': '1690807906',
      'expiry_date': '1690894306',
      'redeemed_date': '1690811520',
      'conversion_date': null,
    },
    {
      'state': 'expired',
      'earn_type': 'stamps',
      'reward_text': 'Free Box of Teabags',
      'headline': 'Expired',
      'voucher_code': 'ddc85cb4-10b3-41a6-a254-35facaf633r3',
      'barcode_type': 0,
      'progress_display_text': '5/5 stamps',
      'current_value': '5',
      'target_value': '5',
      'prefix': null,
      'suffix': 'stamps',
      'body_text': 'Your voucher has expired.',
      'terms_and_conditions': 'https://policies.gb.bink.com/loyalteas/tc.html',
      'issued_date': '1690807862',
      'expiry_date': '1690894262',
      'redeemed_date': null,
      'conversion_date': null,
    }],
    'card': {
      'barcode': null,
      'barcode_type': 0,
      'card_number': 'CORT7908814899',
      'colour': '#439190',
      'text_colour': null,
    },
    'reward_available': true,
    'images': [{
      'id': 1406,
      'type': 0,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/loyalteas-hero.png',
      'description': 'Loyalteas Hero',
      'encoding': 'png',
      'cta_url': null,
    },
    {
      'id': 1408,
      'type': 3,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/loyalteas-icon.png',
      'description': 'Loyalteas Icon',
      'encoding': 'png',
      'cta_url': null,
    }],
    'pll_links': [{
      'payment_account_id': 120802,
      'payment_scheme': 'Visa',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    }],
  }],
  'payment_accounts': [{
    'id': 120802,
    'provider': 'Visa',
    'issuer': 'Barclays',
    'status': 'active',
    'expiry_month': '12',
    'expiry_year': '25',
    'name_on_card': 'Portal Dev',
    'card_nickname': 'Visa Card',
    'type': 'debit',
    'currency_code': 'GBP',
    'country': 'GB',
    'last_four_digits': '5020',
    'images': [{
      'id': 55,
      'type': 0,
      'url': 'https://api.gb.bink.com/content/media/hermes/schemes/Visa-Payment_Eq81MWN.png',
      'description': 'Visa Card Image',
      'encoding': 'png',
    }],
    'pll_links': [{
      'loyalty_card_id': 363707,
      'loyalty_plan': 'Bink Sweet Rewards',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    },
    {
      'loyalty_card_id': 363709,
      'loyalty_plan': 'Loyalteas Plus',
      'status': {
        'state': 'active',
        'slug': null,
        'description': null,
      },
    },
    ],
  },
  ],
}

export const useBankViewport = () => {
  return {
    // Temporary demo wallets
    getDemoWallet0Response,
    getDemoWallet1Response,
    getDemoWallet2Response,
  }
}
