name: build

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        environment: [staging, production]
        include:
          - environment: staging
            portal_api_url: https://portal.staging.gb.bink.com/
            loyalty_api_url: https://api.staging.gb.bink.com/
          - environment: production
            portal_api_url: https://portal.gb.bink.com/
            loyalty_api_url: https://api.gb.bink.com/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            binkcore.azurecr.io/${{ github.event.repository.name }}:${{ matrix.environment }}-${{ github.ref_name }}
            binkcore.azurecr.io/${{ github.event.repository.name }}:${{ matrix.environment }}
          build-args: |
            NEXT_PUBLIC_PORTAL_API_URL=${{ matrix.portal_api_url }}
            NEXT_PUBLIC_LOYALTY_API_URL=${{ matrix.loyalty_api_url }}
            NEXT_PUBLIC_ENV=${{ matrix.environment }}
